// Code generated by open-source/schema/gen-sdk-capabilities.ts — DO NOT EDIT.
// Regenerate via: bun run open-source/schema/gen-sdk-capabilities.ts
//
// This file is the compile-time snapshot of everything this SDK build can
// render. The server uses it (via the X-Orca-Caps-Hash header, shipped in a
// later Epic 25b slice) to decide which features to emit or degrade per
// request. See Epic 25b in .claude/plans/orcagateway-epics.md.
//
// Sources (all under open-source/):
//   schema/protocol.json          → kProtocolVersion
//   sdk/pubspec.yaml              → kSdkSemver
//   schema/widget-registry.json   → kSupportedWidgets
//   engine/src/types/action.ts    → kSupportedActionKinds
//   engine/src/types/value.ts     → kSupportedValueKinds,
//                                    kSupportedTransformKinds,
//                                    kSupportedBoolExprOps

const String kProtocolVersion = '2.0.0';
const String kSdkSemver = '0.1.0';

const Set<String> kSupportedWidgets = {
  'AbsorbPointer',
  'Align',
  'AnimatedAlign',
  'AnimatedBuilder',
  'AnimatedContainer',
  'AnimatedOpacity',
  'AnimatedSwitcher',
  'AppBar',
  'AspectRatio',
  'BackdropFilter',
  'Baseline',
  'BlurView',
  'BottomNavItem',
  'BottomNavigationBar',
  'BottomSheet',
  'Card',
  'Center',
  'Checkbox',
  'CircularProgressIndicator',
  'ClipOval',
  'ClipRRect',
  'ClipRect',
  'ColorFiltered',
  'Column',
  'ConstrainedBox',
  'Container',
  'CustomScrollView',
  'DecoratedBox',
  'DefaultTextStyle',
  'Dialog',
  'Divider',
  'Drawer',
  'ElevatedButton',
  'Expanded',
  'FallbackPrompt',
  'FittedBox',
  'Flexible',
  'FloatingActionButton',
  'Form',
  'FractionallySizedBox',
  'GestureDetector',
  'GridView',
  'Hero',
  'Icon',
  'IconButton',
  'IgnorePointer',
  'Image',
  'ImageIcon',
  'InkWell',
  'InteractiveViewer',
  'IntrinsicHeight',
  'IntrinsicWidth',
  'LimitedBox',
  'LinearProgressIndicator',
  'ListView',
  'Offstage',
  'Opacity',
  'OutlinedButton',
  'Padding',
  'PageView',
  'Positioned',
  'PullToRefresh',
  'Radio',
  'ReorderableListView',
  'RichText',
  'RotatedBox',
  'Row',
  'SafeArea',
  'Scaffold',
  'Scrollbar',
  'SelectableText',
  'SingleChildScrollView',
  'SizedBox',
  'Slider',
  'SliverAppBar',
  'SliverGrid',
  'SliverList',
  'SliverToBoxAdapter',
  'SnackBar',
  'Spacer',
  'Stack',
  'SubPage',
  'Switch',
  'Table',
  'Text',
  'TextButton',
  'TextField',
  'TextFormField',
  'Tooltip',
  'Transform',
  'UnsupportedWidgetPlaceholder',
  'Wrap',
};

const Set<String> kSupportedValueKinds = {
  'conditional',
  'event',
  'info',
  'request',
  'state',
  'static',
  'transform',
  'tween',
  'tweenSequence',
};

const Set<String> kSupportedActionKinds = {
  'actionGroup',
  'addComponent',
  'always',
  'animateForward',
  'animateReverse',
  'clearState',
  'closeDialog',
  'conditionalAction',
  'copyToClipboard',
  'debugLog',
  'deleteComponent',
  'goBack',
  'lifecycle',
  'navigate',
  'once',
  'openDialog',
  'openDrawer',
  'openUrl',
  'persistState',
  'refetchPage',
  'serverAction',
  'setState',
  'share',
  'showSnackbar',
  'showToast',
  'switchTab',
  'updateComponent',
  'updateSubPage',
};

const Set<String> kSupportedTransformKinds = {
  'abs',
  'add',
  'at',
  'ceil',
  'contains',
  'divide',
  'filter',
  'first',
  'floor',
  'formatCurrency',
  'formatDate',
  'formatNumber',
  'join',
  'last',
  'length',
  'map',
  'modulo',
  'multiply',
  'not',
  'regex',
  'round',
  'split',
  'substring',
  'subtract',
  'template',
  'toBool',
  'toFixed',
  'toLowerCase',
  'toString',
  'toUpperCase',
  'trim',
};

const Set<String> kSupportedBoolExprOps = {
  'and',
  'contains',
  'eq',
  'gt',
  'gte',
  'isNull',
  'lt',
  'lte',
  'matches',
  'neq',
  'not',
  'or',
  'startsWith',
};


/// Compile-time snapshot of the capabilities this SDK build advertises.
///
/// Call [toVector] to obtain the full capability map — the shape the
/// server will hash on first contact and cache by hash afterwards. Later
/// Epic 25b slices will send this vector via the X-Orca-Caps-Hash header
/// and fall back to the full-vector body on cache miss.
class SdkCapabilities {
  const SdkCapabilities._();

  static Map<String, dynamic> toVector() => <String, dynamic>{
        'protocolVersion': kProtocolVersion,
        'sdkSemver': kSdkSemver,
        'widgets': kSupportedWidgets.toList()..sort(),
        'valueKinds': kSupportedValueKinds.toList()..sort(),
        'actionKinds': kSupportedActionKinds.toList()..sort(),
        'transformKinds': kSupportedTransformKinds.toList()..sort(),
        'boolExprOps': kSupportedBoolExprOps.toList()..sort(),
      };
}
