export type MaterialIcons = 'home' |
  'home_outlined' |
  'search' |
  'shopping_cart' |
  'shopping_cart_outlined' |
  'shopping_bag' |
  'shopping_bag_outlined' |
  'cart' |
  'person' |
  'person_outlined' |
  'profile' |
  'settings' |
  'settings_outlined' |
  'favorite' |
  'favorite_border' |
  'star' |
  'star_border' |
  'list' |
  'menu' |
  'notifications' |
  'notifications_outlined' |
  'mail' |
  'mail_outlined' |
  'chat' |
  'chat_outlined' |
  'add' |
  'add_circle' |
  'add_circle_outline' |
  'edit' |
  'delete' |
  'delete_outlined' |
  'info' |
  'info_outlined' |
  'help' |
  'help_outlined' |
  'logout' |
  'login' |
  'dashboard' |
  'category' |
  'explore' |
  'history' |
  'bookmark' |
  'bookmark_border' |
  'account_circle' |
  'circle' |
  'close' |
  'check' |
  'check_circle' |
  'arrow_back' |
  'arrow_forward' |
  'arrow_upward' |
  'arrow_downward' |
  'chevron_left' |
  'chevron_right' |
  'expand_more' |
  'expand_less' |
  'more_vert' |
  'more_horiz' |
  'refresh' |
  'share' |
  'copy' |
  'visibility' |
  'visibility_off' |
  'lock' |
  'lock_open' |
  'phone' |
  'email' |
  'location_on' |
  'map' |
  'camera' |
  'camera_alt' |
  'image' |
  'photo' |
  'play_arrow' |
  'pause' |
  'stop' |
  'skip_next' |
  'skip_previous' |
  'volume_up' |
  'volume_off' |
  'wifi' |
  'bluetooth' |
  'dark_mode' |
  'light_mode' |
  'language' |
  'calendar_today' |
  'access_time' |
  'attach_file' |
  'link' |
  'cloud' |
  'cloud_upload' |
  'cloud_download' |
  'file_download' |
  'file_upload' |
  'folder' |
  'description' |
  'receipt' |
  'payment' |
  'credit_card' |
  'local_shipping' |
  'store' |
  'inventory' |
  'thumb_up' |
  'thumb_down' |
  'grade' |
  'warning' |
  'error' |
  'error_outline' |
  'task_alt' |
  'pending' |
  'hourglass_empty' |
  'filter_list' |
  'sort' |
  'tune' |
  'palette' |
  'format_bold' |
  'format_italic' |
  'code' |
  'terminal' |
  'bug_report' |
  'build' |
  'construction' |
  'analytics' |
  'bar_chart' |
  'pie_chart' |
  'trending_up' |
  'trending_down' |
  'speed' |
  'grid_view' |
  'send' |
  'shuffle' |
  'menu_book' |
  'key' |
  'security' |
  'badge' |
  'science' |
  'save' |
  'cloud_off' |
  'tour' |
  'landscape' |
  'architecture' |
  'masjid' |
  'museum' |
  'zoom_out' |
  'zoom_in' |
  'place'|
  'filter_center_focus'|
  'touch_app'|
  'schedule'|
  'stop_circle'|
  'replay_10' |
  'forward_10'|
  'mic'|
  'mic_none'|
  'balance'|
  'open_in_new';
