import '../manifest/plugin_schema.dart';

/// Generates TypeScript source code from a [PluginSchema].
///
/// The output follows the exact patterns used by the Orca Gateway engine:
/// widget classes extending base types, action interfaces extending
/// CustomAction, and PascalCase helper constructors.
class TypeScriptGenerator {
  TypeScriptGenerator._();

  /// Generate a complete TypeScript file from [schema].
  static String generate(String pluginName, PluginSchema schema) {
    final buf = StringBuffer();

    // Header
    buf.writeln('// Auto-generated by orca plugin generate — DO NOT EDIT');
    buf.writeln('// Source: $pluginName/orca_plugin.yaml');
    buf.writeln();

    // Collect imports
    final imports = _collectImports(schema);
    if (imports.typeImports.isNotEmpty) {
      buf.writeln(
          'import type { ${imports.typeImports.join(", ")} } from "orcagateway/types";');
    }
    if (imports.valueImports.isNotEmpty) {
      buf.writeln(
          'import { ${imports.valueImports.join(", ")} } from "orcagateway/types";');
    }
    buf.writeln();

    // Extract and emit named object types
    final emittedObjects = <String>{};
    _emitObjectTypes(buf, schema, emittedObjects);

    // Emit widgets
    if (schema.widgets.isNotEmpty) {
      buf.writeln('// ── Widgets ────────────────────────────────────');
      buf.writeln();
      for (final entry in schema.widgets.entries) {
        _emitWidget(buf, entry.key, entry.value);
      }
    }

    // Emit actions
    if (schema.actions.isNotEmpty) {
      buf.writeln('// ── Actions ────────────────────────────────────');
      buf.writeln();
      for (final entry in schema.actions.entries) {
        _emitAction(buf, entry.key, entry.value);
      }
    }

    return buf.toString();
  }

  // ── Import Collection ─────────────────────────────────

  static _Imports _collectImports(PluginSchema schema) {
    final typeImports = <String>{};
    final valueImports = <String>{};

    if (schema.widgets.isNotEmpty) {
      typeImports.add('Valueable');
      typeImports.add('ActionMap');

      for (final widget in schema.widgets.values) {
        valueImports.add(_baseClass(widget.kind));

        // Check if any prop uses Widget type
        for (final prop in widget.props.values) {
          if (prop.type == 'widget') {
            typeImports.add('Widget');
          }
        }
      }
    }

    if (schema.actions.isNotEmpty) {
      typeImports.add('Value');
      typeImports.add('CustomAction');
    }

    return _Imports(
      typeImports: typeImports.toList()..sort(),
      valueImports: valueImports.toList()..sort(),
    );
  }

  // ── Object Type Extraction ────────────────────────────

  static void _emitObjectTypes(
      StringBuffer buf, PluginSchema schema, Set<String> emitted) {
    final objects = <String, Map<String, PropSchema>>{};

    // Collect from widget props
    for (final widget in schema.widgets.values) {
      _collectObjects(widget.props, objects);
    }
    // Collect from action params
    for (final action in schema.actions.values) {
      _collectObjects(action.params, objects);
    }

    if (objects.isNotEmpty) {
      buf.writeln('// ── Types ──────────────────────────────────────');
      buf.writeln();
      for (final entry in objects.entries) {
        if (emitted.contains(entry.key)) continue;
        emitted.add(entry.key);
        _emitObjectInterface(buf, entry.key, entry.value);
      }
    }
  }

  static void _collectObjects(
      Map<String, PropSchema> props, Map<String, Map<String, PropSchema>> out) {
    for (final prop in props.values) {
      if (prop.type == 'object' &&
          prop.objectName != null &&
          prop.objectProps != null) {
        out[prop.objectName!] = prop.objectProps!;
        // Recurse into nested objects
        _collectObjects(prop.objectProps!, out);
      }
      if (prop.type == 'array' && prop.items != null) {
        final items = prop.items!;
        if (items.type == 'object' &&
            items.objectName != null &&
            items.objectProps != null) {
          out[items.objectName!] = items.objectProps!;
          _collectObjects(items.objectProps!, out);
        }
      }
    }
  }

  static void _emitObjectInterface(
      StringBuffer buf, String name, Map<String, PropSchema> props) {
    buf.writeln('export interface $name {');
    for (final entry in props.entries) {
      final optional = entry.value.required ? '' : '?';
      final tsType = _resolveRawType(entry.value);
      buf.writeln('  ${entry.key}$optional: $tsType;');
    }
    buf.writeln('}');
    buf.writeln();
  }

  // ── Widget Emission ───────────────────────────────────

  static void _emitWidget(
      StringBuffer buf, String name, WidgetSchema widget) {
    final kind = widget.kind;
    final baseClass = _baseClass(kind);
    final hasChild = kind == 'button' || kind == 'layout-single';
    final hasChildren = kind == 'layout-multi';

    // Props interface
    buf.writeln('export interface ${name}Props {');
    if (hasChild) {
      buf.writeln('  child?: Widget;');
    }
    if (hasChildren) {
      buf.writeln('  children: Widget[];');
    }
    for (final entry in widget.props.entries) {
      final optional = entry.value.required ? '' : '?';
      final tsType = _resolveValueableType(entry.value);
      buf.writeln('  ${entry.key}$optional: $tsType;');
    }
    // Actions prop
    if (widget.triggers.isNotEmpty) {
      final triggerUnion =
          widget.triggers.map((t) => "'$t'").join(' | ');
      buf.writeln('  actions?: ActionMap<$triggerUnion>;');
    } else {
      buf.writeln('  actions?: ActionMap;');
    }
    buf.writeln('}');
    buf.writeln();

    // Compute Omit type
    final omitFields = <String>["actions"];
    if (hasChild) omitFields.insert(0, "child");
    if (hasChildren) omitFields.insert(0, "children");
    final omitStr = omitFields.map((f) => '"$f"').join(' | ');

    // Widget class
    buf.writeln('export class $name extends $baseClass {');
    buf.writeln('  readonly type = "$name";');
    buf.writeln('  private props: Omit<${name}Props, $omitStr>;');
    buf.writeln();
    buf.writeln('  private constructor(opts: ${name}Props) {');
    buf.writeln('    super();');
    if (hasChild) {
      buf.writeln('    this.child = opts.child;');
    }
    if (hasChildren) {
      buf.writeln('    this.children = opts.children;');
    }
    buf.writeln('    this.actions = opts.actions;');

    // Destructure to separate handled fields from props
    final destructured = <String>[];
    if (hasChild) destructured.add('child: _c');
    if (hasChildren) destructured.add('children: _ch');
    destructured.add('actions: _');
    buf.writeln(
        '    const { ${destructured.join(", ")}, ...rest } = opts;');
    buf.writeln('    this.props = rest;');
    buf.writeln('  }');
    buf.writeln();
    buf.writeln(
        '  static new(opts: ${name}Props): $name { return new $name(opts); }');
    buf.writeln(
        '  getProps(): Record<string, unknown> { return { ...this.props }; }');
    buf.writeln('}');
    buf.writeln();
  }

  // ── Action Emission ───────────────────────────────────

  static void _emitAction(
      StringBuffer buf, String actionType, ActionSchema action) {
    final pascalName = _toPascalCase(actionType);

    // Action interface
    buf.writeln('export interface ${pascalName}Action extends CustomAction {');
    buf.writeln('  type: "$actionType";');
    for (final entry in action.params.entries) {
      final optional = entry.value.required ? '' : '?';
      final tsType = _resolveActionParamType(entry.value);
      buf.writeln('  ${entry.key}$optional: $tsType;');
    }
    buf.writeln('}');
    buf.writeln();

    // Helper function — required params first, then optional
    final requiredParams = <MapEntry<String, PropSchema>>[];
    final optionalParams = <MapEntry<String, PropSchema>>[];
    for (final entry in action.params.entries) {
      if (entry.value.required) {
        requiredParams.add(entry);
      } else {
        optionalParams.add(entry);
      }
    }
    final orderedParams = [...requiredParams, ...optionalParams];

    final paramList = orderedParams.map((e) {
      final optional = e.value.required ? '' : '?';
      final tsType = _resolveActionParamType(e.value);
      return '${e.key}$optional: $tsType';
    }).join(', ');

    final returnFields =
        action.params.keys.map((k) => k).join(', ');

    buf.writeln(
        'export function $pascalName($paramList): ${pascalName}Action {');
    buf.writeln(
        '  return { type: "$actionType", $returnFields };');
    buf.writeln('}');
    buf.writeln();
  }

  // ── Type Resolution Helpers ───────────────────────────

  /// Resolve a prop type for widget props (wrapped in Valueable<T>).
  static String _resolveValueableType(PropSchema prop) {
    if (prop.type == 'widget') return 'Widget';

    final inner = _resolveRawType(prop);
    return 'Valueable<$inner>';
  }

  /// Resolve a prop type for action params (uses Value | T for non-strings).
  static String _resolveActionParamType(PropSchema prop) {
    if (prop.type == 'string') {
      if (prop.enumValues != null && prop.enumValues!.isNotEmpty) {
        return prop.enumValues!.map((v) => '"$v"').join(' | ');
      }
      return 'string';
    }
    if (prop.type == 'number') return 'Value | number';
    if (prop.type == 'boolean') return 'Value | boolean';
    if (prop.type == 'object' && prop.objectName != null) {
      return prop.objectName!;
    }
    if (prop.type == 'array' && prop.items != null) {
      return '${_resolveRawType(prop.items!)}[]';
    }
    return 'unknown';
  }

  /// Resolve the raw (unwrapped) TypeScript type for a prop.
  static String _resolveRawType(PropSchema prop) {
    switch (prop.type) {
      case 'string':
        if (prop.enumValues != null && prop.enumValues!.isNotEmpty) {
          return prop.enumValues!.map((v) => '"$v"').join(' | ');
        }
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'object':
        if (prop.objectName != null) return prop.objectName!;
        // Inline anonymous object
        if (prop.objectProps != null) {
          final fields = prop.objectProps!.entries.map((e) {
            final optional = e.value.required ? '' : '?';
            return '${e.key}$optional: ${_resolveRawType(e.value)}';
          }).join('; ');
          return '{ $fields }';
        }
        return 'Record<string, unknown>';
      case 'array':
        if (prop.items != null) {
          return '${_resolveRawType(prop.items!)}[]';
        }
        return 'unknown[]';
      case 'widget':
        return 'Widget';
      default:
        return 'unknown';
    }
  }

  /// Map widget kind to TypeScript base class name.
  static String _baseClass(String kind) {
    return switch (kind) {
      'primitive' => 'PrimitiveWidget',
      'input' => 'InputWidget',
      'button' => 'ButtonWidget',
      'layout-single' => 'SingleChildLayout',
      'layout-multi' => 'MultiChildLayout',
      _ => 'PrimitiveWidget',
    };
  }

  /// Convert a camelCase action name to PascalCase.
  static String _toPascalCase(String name) {
    if (name.isEmpty) return name;
    return '${name[0].toUpperCase()}${name.substring(1)}';
  }
}

class _Imports {
  final List<String> typeImports;
  final List<String> valueImports;
  _Imports({required this.typeImports, required this.valueImports});
}
