// Auto-generated by orca plugin generate — DO NOT EDIT
// Source: orca_google_map/orca_plugin.yaml

import type { ActionMap, CustomAction, Value, Valueable } from "../../engine/src/types";
import { PrimitiveWidget } from "../../engine/src/types";

// ── Types ──────────────────────────────────────

export interface MapMarker {
  id: string;
  latitude: number;
  longitude: number;
  title?: string;
  snippet?: string;
}

// ── Widgets ────────────────────────────────────

export interface GoogleMapProps {
  latitude: Valueable<number>;
  longitude: Valueable<number>;
  zoom?: Valueable<number>;
  mapType?: Valueable<"normal" | "satellite" | "terrain" | "hybrid">;
  myLocationEnabled?: Valueable<boolean>;
  zoomControlsEnabled?: Valueable<boolean>;
  markers?: Valueable<MapMarker[]>;
  actions?: ActionMap<'onTap' | 'onLongPress' | 'onCameraMove' | 'onMarkerTap'>;
}

export class GoogleMap extends PrimitiveWidget {
  readonly type = "GoogleMap";
  private props: Omit<GoogleMapProps, "actions">;

  private constructor(opts: GoogleMapProps) {
    super();
    this.actions = opts.actions;
    const { actions: _, ...rest } = opts;
    this.props = rest;
  }

  static new(opts: GoogleMapProps): GoogleMap { return new GoogleMap(opts); }
  getProps(): Record<string, unknown> { return { ...this.props }; }
}

// ── Actions ────────────────────────────────────

export interface MoveCameraAction extends CustomAction {
  type: "moveCamera";
  targetId: string;
  latitude: Value | number;
  longitude: Value | number;
  zoom?: Value | number;
}

export function MoveCamera(targetId: string, latitude: Value | number, longitude: Value | number, zoom?: Value | number): MoveCameraAction {
  return { type: "moveCamera", targetId, latitude, longitude, zoom };
}

