// Declarative preview stub for orca_google_map (Epic 38 Slice B).
//
// Each key is a widget type this plugin provides. Each value is an Orca Gateway
// engine Widget tree built from CORE widgets only — referencing another
// plugin's widgets would defeat the "no rebuild needed" property and is
// rejected by `orca plugin doctor`.
//
// The compiled artifact at preview/stub.compiled.json is regenerated by
// `orca plugin build` and is committed into the plugin repo so consumers
// don't need a build step.

import {
  Column,
  Container,
  Text,
  Icon,
  SizedBox,
  EdgeInsets,
  BoxDecoration,
  Color,
} from "../../../engine/src/components";
import type { Widget } from "../../../engine/src/types/widget";

const stubs: Record<string, Widget> = {
  GoogleMap: Container.new({
    height: 240,
    padding: EdgeInsets.all(16),
    decoration: BoxDecoration({
      color: Color("#E5E7EB"),
      borderRadius: 12,
    }),
    child: Column.new({
      children: [
        Icon.new({ name: "map", size: 32 }),
        SizedBox.new({ height: 8 }),
        Text.new({ data: "Google Maps preview" }),
        SizedBox.new({ height: 4 }),
        Text.new({ data: "Runs in the compiled mobile app" }),
      ],
    }),
  }),
};

export default stubs;
