// GENERATED FILE — DO NOT EDIT
// Source: schema/widget-registry.json
// Run: dart run tool/gen_widget_registry.dart

class WidgetRegistryEntry {
  final String type;
  final String kind;
  final String childMode;
  final List<String> slots;
  final String introducedIn;
  final String? removedIn;
  final bool frozen;
  final bool isSupportedOnWeb;

  const WidgetRegistryEntry({
    required this.type,
    required this.kind,
    required this.childMode,
    this.slots = const [],
    this.introducedIn = '1.0.0',
    this.removedIn,
    this.frozen = false,
    this.isSupportedOnWeb = true,
  });
}

const Map<String, WidgetRegistryEntry> widgetRegistry = {
  'AbsorbPointer': WidgetRegistryEntry(type: 'AbsorbPointer', kind: 'layout', childMode: 'single'),
  'Align': WidgetRegistryEntry(type: 'Align', kind: 'layout', childMode: 'single'),
  'AnimatedAlign': WidgetRegistryEntry(type: 'AnimatedAlign', kind: 'layout', childMode: 'single'),
  'AnimatedBuilder': WidgetRegistryEntry(type: 'AnimatedBuilder', kind: 'layout', childMode: 'multi'),
  'AnimatedContainer': WidgetRegistryEntry(type: 'AnimatedContainer', kind: 'layout', childMode: 'single'),
  'AnimatedOpacity': WidgetRegistryEntry(type: 'AnimatedOpacity', kind: 'layout', childMode: 'single'),
  'AnimatedSwitcher': WidgetRegistryEntry(type: 'AnimatedSwitcher', kind: 'layout', childMode: 'single'),
  'AppBar': WidgetRegistryEntry(type: 'AppBar', kind: 'structure', childMode: 'none', slots: ['title', 'leading']),
  'AspectRatio': WidgetRegistryEntry(type: 'AspectRatio', kind: 'layout', childMode: 'single'),
  'BackdropFilter': WidgetRegistryEntry(type: 'BackdropFilter', kind: 'layout', childMode: 'single'),
  'Baseline': WidgetRegistryEntry(type: 'Baseline', kind: 'layout', childMode: 'single'),
  'BlurView': WidgetRegistryEntry(type: 'BlurView', kind: 'layout', childMode: 'single'),
  'BottomNavigationBar': WidgetRegistryEntry(type: 'BottomNavigationBar', kind: 'structure', childMode: 'none'),
  'BottomNavItem': WidgetRegistryEntry(type: 'BottomNavItem', kind: 'primitive', childMode: 'none'),
  'BottomSheet': WidgetRegistryEntry(type: 'BottomSheet', kind: 'layout', childMode: 'single'),
  'Card': WidgetRegistryEntry(type: 'Card', kind: 'layout', childMode: 'single'),
  'Center': WidgetRegistryEntry(type: 'Center', kind: 'layout', childMode: 'single'),
  'Checkbox': WidgetRegistryEntry(type: 'Checkbox', kind: 'input', childMode: 'none'),
  'CircularProgressIndicator': WidgetRegistryEntry(type: 'CircularProgressIndicator', kind: 'primitive', childMode: 'none'),
  'ClipOval': WidgetRegistryEntry(type: 'ClipOval', kind: 'layout', childMode: 'single'),
  'ClipRect': WidgetRegistryEntry(type: 'ClipRect', kind: 'layout', childMode: 'single'),
  'ClipRRect': WidgetRegistryEntry(type: 'ClipRRect', kind: 'layout', childMode: 'single'),
  'ColorFiltered': WidgetRegistryEntry(type: 'ColorFiltered', kind: 'layout', childMode: 'single'),
  'Column': WidgetRegistryEntry(type: 'Column', kind: 'layout', childMode: 'multi'),
  'ConstrainedBox': WidgetRegistryEntry(type: 'ConstrainedBox', kind: 'layout', childMode: 'single'),
  'Container': WidgetRegistryEntry(type: 'Container', kind: 'layout', childMode: 'single'),
  'CustomScrollView': WidgetRegistryEntry(type: 'CustomScrollView', kind: 'layout', childMode: 'multi'),
  'DecoratedBox': WidgetRegistryEntry(type: 'DecoratedBox', kind: 'layout', childMode: 'single'),
  'DefaultTextStyle': WidgetRegistryEntry(type: 'DefaultTextStyle', kind: 'layout', childMode: 'single'),
  'Dialog': WidgetRegistryEntry(type: 'Dialog', kind: 'layout', childMode: 'single'),
  'Divider': WidgetRegistryEntry(type: 'Divider', kind: 'primitive', childMode: 'none'),
  'Drawer': WidgetRegistryEntry(type: 'Drawer', kind: 'layout', childMode: 'single'),
  'ElevatedButton': WidgetRegistryEntry(type: 'ElevatedButton', kind: 'button', childMode: 'single'),
  'Expanded': WidgetRegistryEntry(type: 'Expanded', kind: 'layout', childMode: 'single'),
  'FallbackPrompt': WidgetRegistryEntry(type: 'FallbackPrompt', kind: 'primitive', childMode: 'none', frozen: true),
  'FittedBox': WidgetRegistryEntry(type: 'FittedBox', kind: 'layout', childMode: 'single'),
  'Flexible': WidgetRegistryEntry(type: 'Flexible', kind: 'layout', childMode: 'single'),
  'FloatingActionButton': WidgetRegistryEntry(type: 'FloatingActionButton', kind: 'button', childMode: 'single'),
  'Form': WidgetRegistryEntry(type: 'Form', kind: 'layout', childMode: 'single'),
  'FractionallySizedBox': WidgetRegistryEntry(type: 'FractionallySizedBox', kind: 'layout', childMode: 'single'),
  'GestureDetector': WidgetRegistryEntry(type: 'GestureDetector', kind: 'layout', childMode: 'single'),
  'GridView': WidgetRegistryEntry(type: 'GridView', kind: 'layout', childMode: 'multi'),
  'Hero': WidgetRegistryEntry(type: 'Hero', kind: 'layout', childMode: 'single'),
  'Icon': WidgetRegistryEntry(type: 'Icon', kind: 'primitive', childMode: 'none'),
  'IconButton': WidgetRegistryEntry(type: 'IconButton', kind: 'button', childMode: 'single'),
  'IgnorePointer': WidgetRegistryEntry(type: 'IgnorePointer', kind: 'layout', childMode: 'single'),
  'Image': WidgetRegistryEntry(type: 'Image', kind: 'primitive', childMode: 'none'),
  'ImageIcon': WidgetRegistryEntry(type: 'ImageIcon', kind: 'primitive', childMode: 'none'),
  'InkWell': WidgetRegistryEntry(type: 'InkWell', kind: 'layout', childMode: 'single'),
  'InteractiveViewer': WidgetRegistryEntry(type: 'InteractiveViewer', kind: 'layout', childMode: 'single'),
  'IntrinsicHeight': WidgetRegistryEntry(type: 'IntrinsicHeight', kind: 'layout', childMode: 'single'),
  'IntrinsicWidth': WidgetRegistryEntry(type: 'IntrinsicWidth', kind: 'layout', childMode: 'single'),
  'LimitedBox': WidgetRegistryEntry(type: 'LimitedBox', kind: 'layout', childMode: 'single'),
  'LinearProgressIndicator': WidgetRegistryEntry(type: 'LinearProgressIndicator', kind: 'primitive', childMode: 'none'),
  'ListView': WidgetRegistryEntry(type: 'ListView', kind: 'layout', childMode: 'multi'),
  'Offstage': WidgetRegistryEntry(type: 'Offstage', kind: 'layout', childMode: 'single'),
  'Opacity': WidgetRegistryEntry(type: 'Opacity', kind: 'layout', childMode: 'single'),
  'OutlinedButton': WidgetRegistryEntry(type: 'OutlinedButton', kind: 'button', childMode: 'single'),
  'Padding': WidgetRegistryEntry(type: 'Padding', kind: 'layout', childMode: 'single'),
  'PageView': WidgetRegistryEntry(type: 'PageView', kind: 'layout', childMode: 'multi'),
  'Positioned': WidgetRegistryEntry(type: 'Positioned', kind: 'layout', childMode: 'single'),
  'PullToRefresh': WidgetRegistryEntry(type: 'PullToRefresh', kind: 'layout', childMode: 'single'),
  'Radio': WidgetRegistryEntry(type: 'Radio', kind: 'input', childMode: 'none'),
  'ReorderableListView': WidgetRegistryEntry(type: 'ReorderableListView', kind: 'layout', childMode: 'multi'),
  'RichText': WidgetRegistryEntry(type: 'RichText', kind: 'primitive', childMode: 'none'),
  'RotatedBox': WidgetRegistryEntry(type: 'RotatedBox', kind: 'layout', childMode: 'single'),
  'Row': WidgetRegistryEntry(type: 'Row', kind: 'layout', childMode: 'multi'),
  'SafeArea': WidgetRegistryEntry(type: 'SafeArea', kind: 'layout', childMode: 'single'),
  'Scaffold': WidgetRegistryEntry(type: 'Scaffold', kind: 'structure', childMode: 'none', slots: ['appBar', 'body', 'floatingActionButton', 'bottomNavigationBar', 'drawer']),
  'Scrollbar': WidgetRegistryEntry(type: 'Scrollbar', kind: 'layout', childMode: 'single'),
  'SelectableText': WidgetRegistryEntry(type: 'SelectableText', kind: 'primitive', childMode: 'none'),
  'SingleChildScrollView': WidgetRegistryEntry(type: 'SingleChildScrollView', kind: 'layout', childMode: 'single'),
  'SizedBox': WidgetRegistryEntry(type: 'SizedBox', kind: 'layout', childMode: 'single'),
  'Slider': WidgetRegistryEntry(type: 'Slider', kind: 'input', childMode: 'none'),
  'SliverAppBar': WidgetRegistryEntry(type: 'SliverAppBar', kind: 'structure', childMode: 'none', slots: ['title', 'leading', 'flexibleSpace']),
  'SliverGrid': WidgetRegistryEntry(type: 'SliverGrid', kind: 'layout', childMode: 'multi'),
  'SliverList': WidgetRegistryEntry(type: 'SliverList', kind: 'layout', childMode: 'multi'),
  'SliverToBoxAdapter': WidgetRegistryEntry(type: 'SliverToBoxAdapter', kind: 'layout', childMode: 'single'),
  'SnackBar': WidgetRegistryEntry(type: 'SnackBar', kind: 'primitive', childMode: 'none'),
  'Spacer': WidgetRegistryEntry(type: 'Spacer', kind: 'primitive', childMode: 'none'),
  'Stack': WidgetRegistryEntry(type: 'Stack', kind: 'layout', childMode: 'multi'),
  'SubPage': WidgetRegistryEntry(type: 'SubPage', kind: 'layout', childMode: 'single'),
  'Switch': WidgetRegistryEntry(type: 'Switch', kind: 'input', childMode: 'none'),
  'Table': WidgetRegistryEntry(type: 'Table', kind: 'layout', childMode: 'multi'),
  'Text': WidgetRegistryEntry(type: 'Text', kind: 'primitive', childMode: 'none'),
  'TextButton': WidgetRegistryEntry(type: 'TextButton', kind: 'button', childMode: 'single'),
  'TextField': WidgetRegistryEntry(type: 'TextField', kind: 'input', childMode: 'none'),
  'TextFormField': WidgetRegistryEntry(type: 'TextFormField', kind: 'input', childMode: 'none'),
  'Tooltip': WidgetRegistryEntry(type: 'Tooltip', kind: 'layout', childMode: 'single'),
  'Transform': WidgetRegistryEntry(type: 'Transform', kind: 'layout', childMode: 'single'),
  'UnsupportedWidgetPlaceholder': WidgetRegistryEntry(type: 'UnsupportedWidgetPlaceholder', kind: 'primitive', childMode: 'none'),
  'Wrap': WidgetRegistryEntry(type: 'Wrap', kind: 'layout', childMode: 'multi'),
};
